title: RPG Studio Devlog
description: Acompanhe o desenvolvimento do RPG Studio
theme: jekyll-theme-cayman
baseurl: ""
url: "https://pedro-coleone.github.io/rpg-studio-blog" # ajuste se usar outro nome de usuário
lang: pt-BR

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name: Pedro Coleone
  url: https://github.com/pedro-coleone

markdown: kramdown