title: RPG Studio Devlog
description: Acompanhe o desenvolvimento do RPG Studio
theme: jekyll-theme-cayman
baseurl: "/rpg-studio-blog"
url: "https://rpg-studio-admin.github.io/rpg-studio-blog"
lang: pt-BR

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name: RPG Studio
  url: https://github.com/rpg-studio-admin

markdown: kramdown